### ISSUE TITLE
Controls are messed up and unconfigurable at all 

### ISSUE THREAD

**Issue by JrRadiant** [Moehammered/switch-remote-play#8] opened 2021-01-31 19:43 UTC
Hi Moehammered! Thank you for your great work!

Unfortunately, all is good for me except the gamepad controls and it's buttons, it just all messed up — i. e. pressing any buttons are causing phantom, for example A = pressing Y, B is = C, moving left stick = pressing all buttons in random order, etc.

I tried both the Xbox 360 preset and DualShock 4 profile, none of them are works for me.

And I cannot configure it via the Hardware Gamepad manager in Windows, too.

My PC configuration is:

Windows 7 with installed KB3033929-x64.msu, Setup.Screen.Capturer.Recorder.v0.12.11.exe, ViGEmBus_Setup_1.16.116.exe and Xbox360_64Eng.exe.

Network: Wifi 5Ghz
CPU: Intel 3770
RAM: 24GB 1600 Mhz
GPU: AMD R9 Fury
SSD: 128 GB

My Switch configuration is:

CPU, RAM: no overclock
CFW: Atmosphere M.17.1
System FW: 11.0.1
CFW on NAND (not emummc)

Help, please. (:

**Comment by JrRadiant** [comment] 2021-01-31 20:05
It looks like this in the Setting menu (sorry for foreign for you Russian language), all buttons are messed up:
![scr](https://user-images.githubusercontent.com/61790774/106396419-fe722280-6431-11eb-9a4f-046c971db4ce.jpg)

**Comment by Moehammered** [comment] 2021-01-31 20:26
Hi there Radiant,

I'm very sorry to hear that it's causing issues for you. Thank you for providing your system information :)

I've had this issue once in the past when I accidentally used an old version of switch remote play. I have personally never tested it on Windows 7 but I will make a virtual machine to test and see if I can recreate the issue you are experiencing.

I'm assuming you're using the latest version of switch remote play? Version should be 0.8.1.

Can you try uninstalling ViGEm Bus Driver and reinstalling it? Please make sure to use version 1.16 as version 1.17 or newer is not compatible with Windows 7.

Hopefully we can fix this. :)

**Comment by JrRadiant** [comment] 2021-01-31 21:14
Yep, it's version is 0.8.1 and ViGEm is v1.16, reinstalled it and 0 effect at all.:(

I will wait for your research with the Win7 VM, thank you!

**Comment by Moehammered** [comment] 2021-02-02 10:45
Hello JrRadiant.

I have some wonderful news. I have spent the past 2 days testing the bug in Windows 7 on my VM and I have finally discovered what was causing it. I am fairly busy nowadays but I will release a new build within the next 24 ~ 48 hours. I'm sorry I can't do it earlier. Thank you for being patient.

I very much appreciate your detailed error report. You helped me discover a very annoying and serious bug that can potentially occur randomly depending on the network hardware.

Please check the releases within the next 48 hours for the fix. Please test it and let me know if the issue is fixed you at that time :)

**Comment by JrRadiant** [comment] 2021-02-02 11:11
OMG, thank you very much!.. Please take your time, I'll wait patiently.

Thank you!

**Comment by Moehammered** [comment] 2021-02-03 10:26
> OMG, thank you very much!.. Please take your time, I'll wait patiently.
> 
> Thank you!

Hey JrRadiant,

Can you please test the attached version of the program and let me know if the controller works normally?

Just overwrite switch-remote-play-host.exe with the attached version and attempt to connect to it.

Before I make a release, I'd like to let you test it first just to make sure the issue you're experiencing is resolved.

Thanks :)
[switch-remote-play-host_controller-patch.zip](https://github.com/Moehammered/switch-remote-play/files/5917702/switch-remote-play-host_controller-patch.zip)

**Comment by JrRadiant** [comment] 2021-02-03 10:35
Wow, super!..
Works as good as intended with Xbox 360 Controller Mode.

Many thanks!

**Comment by Moehammered** [comment] 2021-02-03 11:12
I'm very happy to hear that!

I will close this issue when I make the next release. If the controller issue occurs for you again in the new release, feel free to reopen this issue at that time.

Thanks for reporting the issue and being patient.

Enjoy!

**Comment by JrRadiant** [comment] 2021-02-03 14:12
Thanks!

Unfortunately, found out another bug: once in a 1-2 minutes, all buttons are pressing randomly. :(

I made a video for you to investigate it:
https://user-images.githubusercontent.com/61790774/106758713-0dd4b400-665c-11eb-91e0-ed50ddf62ff7.mp4

**Comment by Moehammered** [comment] 2021-02-03 20:26
Thanks for the video demonstration. It seems to look like the same bug. If you do the same thing for a few minutes without using the analog sticks but instead other buttons, does it occur?

The patch I made was to fix some cases where the controller data was sent partially and therefore would be corrupt when read as input. It looks like it is still occurring.

Thanks for testing the patch for me. I'll investigate this again tonight and see if I can get the bug to occur.

Could you please attach a screenshot of all the console text when you first startup switch remote play host? I'd like to see the diagnostic info it displays on your machine.

**Comment by JrRadiant** [comment] 2021-02-04 04:34
Yep, but I guess it happens less often without using analog sticks.

Here's full console log text:
[console_text.txt](https://github.com/Moehammered/switch-remote-play/files/5923199/console_text.txt)

**Comment by Moehammered** [comment] 2021-02-04 09:28
Hey JrRadiant,

I double checked the code and I had a silly little mistake. Please test this patched version and let me know if the issue is still happening for you.

[switch-remote-play-host_controller-patch.zip](https://github.com/Moehammered/switch-remote-play/files/5924575/switch-remote-play-host_controller-patch.zip)

**Comment by JrRadiant** [comment] 2021-02-04 10:05
Wow, much better, key buttons (ABXY and so on) seems to not pressing all at once for now, appreciate it!..

Analog stick ghosting is present, I guess — in this short 23 sec video, on 00:03 and 00:20 sec there're saccades of sticks to the center of it (to a neutral position), while I move them in a circle way all time:

https://user-images.githubusercontent.com/61790774/106877245-bf2e2500-6702-11eb-8c54-6b2ef14ace5a.mp4

**Comment by Moehammered** [comment] 2021-02-04 11:23
Hmmm. I noticed it would happen a little bit for me but I figured maybe it was due to the VM networking.

If you hold the stick in one position for a while does it still have some ghosting? (for example, hold the stick up for 25 seconds?)

Also does your PC have WiFi? I'm curious if the issue occurs on both WiFi and ethernet. If you can test via your PC connected to WiFi as well I'd appreciate that.

**Comment by JrRadiant** [comment] 2021-02-04 11:44
Yep, it's still the same when holding in one position:

https://user-images.githubusercontent.com/61790774/106887957-18508580-6710-11eb-929e-2b6ed1a2e1b1.mp4

Don't have a WiFi module for PC right now, but if I'll find any I'll try to test it with.

**Comment by Moehammered** [comment] 2021-02-04 11:58
OK thanks for checking that for me. I'll investigate it tomorrow. If I figure out the cause I'll make a patch and post it here.
Thank you very much for your effort testing this out and reporting it :)

**Comment by Moehammered** [comment] 2021-02-05 06:39
Hey JrRadiant, 

I've found the issue. It was a different issue than the first one. The first bug was from corrupt network data(which is fixed). This 'ghosting' bug is from the X360 controller resetting every single frame. I've patched it up.

Please test the attached version and let me know if the issue has gone away for you.

[switch-remote-play-host_controller-patch-v2.zip](https://github.com/Moehammered/switch-remote-play/files/5930613/switch-remote-play-host_controller-patch-v2.zip)

**Comment by JrRadiant** [comment] 2021-02-05 07:16
Super, now it's seems rock-solid. 

Thank you again!

**Comment by Moehammered** [comment] 2021-02-05 07:20
Awesome! I'm glad it's working.

Yeah if future issues happen, feel free to write them.

Thank you very much for your testing. You helped me find 2 critical bugs. :)

I'll be making a release sometime soon, so if the new release causes this issue again please let me know.

Have fun!

(P.S. I will close this issue once I make a public release with this patch included.)

**Comment by Moehammered** [comment] 2021-02-07 11:37
Hey JrRadiant,

Sorry to bother you, but could you test the latest release and let me know if the controller works well?
https://github.com/Moehammered/switch-remote-play/releases/latest

Thanks.

**Comment by JrRadiant** [comment] 2021-02-07 12:23
Thank you for the update, works good as always!

**Comment by Moehammered** [comment] 2021-02-07 12:32
Thank you for testing the latest release. Have a nice day. :)

**Closed by Moehammered** 2021-02-07 12:32 UTC
